language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

notifications:
    email:
        recipients:
            - 931180361@qq.com #你的邮箱地址
        on_success: change
        on_failure: always

# turn off the clone of submodules for change the SSH to HTTPS in .gitmodules to avoid the error
git:
  submodules: false
        
before_install:
    - export TZ='Asia/Shanghai'
    - npm install hexo-cli -g

install:
    - npm install

script:
    - hexo clean
    - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "scofield.yu"
  - git config user.email "931180361@qq.com"
  - git add .
  - git commit -m "Update blog content by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" main:main

branches:
    only:
        - master

env:
    global:
        # Github Pages
        - GH_REF: https://github.com/Scofieldsu/Scofieldsu.github.io
        # Coding Pages
        - CD_REF: git@github.com:Scofieldsu/blog-source.git
